name: Run Unittests
on: [push, pull_request]

jobs:
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dc: [dmd-latest, ldc-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - name: Install D compiler
        uses: mihails-strasuns/setup-dlang@v0.5.0
        with:
          compiler: ${{ matrix.dc }}

      - name: Install apk-tools
        run: |
          git clone https://gitlab.alpinelinux.org/Cogitri/apk-tools.git/
          cd apk-tools
          git checkout make
          make CFLAGS="$CFLAGS -Wno-error" SCDOC="" LUAAPK=""
          sudo make CFLAGS="$CFLAGS -Wno-error" SCDOC="" LUAAPK="" install

      - name: Run dub tests
        run: |
          dub test
